package org.eclipse.safari.jikespg.parser;

public interface JikesPGLexerexp {
    public final static int
      ALIAS_KEY = 1,
      AST_KEY = 2,
      DEFINE_KEY = 3,
      DISJOINTPREDECESSORSETS_KEY = 4,
      DROPRULES_KEY = 5,
      DROPSYMBOLS_KEY = 6,
      EMPTY_KEY = 7,
      END_KEY = 8,
      ERROR_KEY = 9,
      EOL_KEY = 10,
      EOF_KEY = 11,
      EXPORT_KEY = 12,
      GLOBALS_KEY = 13,
      HEADERS_KEY = 14,
      IDENTIFIER_KEY = 15,
      IMPORT_KEY = 16,
      INCLUDE_KEY = 17,
      KEYWORDS_KEY = 18,
      NAMES_KEY = 19,
      NOTICE_KEY = 20,
      OPTIONS_KEY = 21,
      RECOVER_KEY = 22,
      TERMINALS_KEY = 23,
      RULES_KEY = 24,
      START_KEY = 25,
      TRAILERS_KEY = 26,
      TYPES_KEY = 27,
      EOF_TOKEN = 28,
      SINGLE_LINE_COMMENT = 29,
      MACRO_NAME = 30,
      SYMBOL = 31,
      BLOCK = 32,
      EQUIVALENCE = 33,
      PRIORITY_EQUIVALENCE = 34,
      ARROW = 35,
      PRIORITY_ARROW = 36,
      OR_MARKER = 37,
      EQUAL = 38,
      COMMA = 39,
      LEFT_PAREN = 40,
      RIGHT_PAREN = 41;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "ALIAS_KEY",
                 "AST_KEY",
                 "DEFINE_KEY",
                 "DISJOINTPREDECESSORSETS_KEY",
                 "DROPRULES_KEY",
                 "DROPSYMBOLS_KEY",
                 "EMPTY_KEY",
                 "END_KEY",
                 "ERROR_KEY",
                 "EOL_KEY",
                 "EOF_KEY",
                 "EXPORT_KEY",
                 "GLOBALS_KEY",
                 "HEADERS_KEY",
                 "IDENTIFIER_KEY",
                 "IMPORT_KEY",
                 "INCLUDE_KEY",
                 "KEYWORDS_KEY",
                 "NAMES_KEY",
                 "NOTICE_KEY",
                 "OPTIONS_KEY",
                 "RECOVER_KEY",
                 "TERMINALS_KEY",
                 "RULES_KEY",
                 "START_KEY",
                 "TRAILERS_KEY",
                 "TYPES_KEY",
                 "EOF_TOKEN",
                 "SINGLE_LINE_COMMENT",
                 "MACRO_NAME",
                 "SYMBOL",
                 "BLOCK",
                 "EQUIVALENCE",
                 "PRIORITY_EQUIVALENCE",
                 "ARROW",
                 "PRIORITY_ARROW",
                 "OR_MARKER",
                 "EQUAL",
                 "COMMA",
                 "LEFT_PAREN",
                 "RIGHT_PAREN"
             };


    public final static boolean isValidForParser = false;
}
